header:
    text: Mortazavi Lab at UC Irvine
    title: Genomics, computation and sequencing

services:
    title: "Research"
    text: "There are many diverse projects going on in the lab"
    section: services
    list:
      - title: "[ENCODE](https://www.encodeproject.org/)"
        desc: "We are an ENCODE production lab and produce and analyze long-read and micro RNA-seq datasets for the consortium."
        icon: fas fa-dna #find more at https://fontawesome.com/icons
      - title: "[Model AD](https://www.model-ad.org/)"
        desc: "Working towards developing a more comprehensive mouse model for Alzheimer's Disease."
        icon: fas fa-brain       
      - title: "FSHD"
        desc: "Understanding the mechanisms behind the pathology in Facioscapulohumeral muscular dystrophy."
        icon: fas fa-male


portfolio:
    title: "Software"
    text: "Software produced by the lab used to analyze genomics data"
    section: portfolio
    
team:
    title: "People"
    # text: ""
    # subtext: ""
    section: team
    people:
      - name: "Narges Rezaie"
        id: "narges"
        role: "MCSB PhD Student"
        image: assets/img/team/narges.png
        info: "
            **Research Interests:**
            \nAs a person with a computer science background, I've always been interested in machine learning methods, network analysis and their applications.
            Currently, I find the brain as an interesting organ, so I'm trying to identify and classify every functional part of the genome in the brain.
            \n\n
            **Links:**
            \n**Personal Website (https://hpc.oit.uci.edu/~nargesr/)**
            \n[**Google Scholar**](https://scholar.google.com/citations?user=xS23yQUAAAAJ&hl=en)
            \n[**ORCID**](https://orcid.org/0000-0001-9326-9954)
            \n[**LinkedIn**](https://www.linkedin.com/in/narges-rezaie-ab9710b8/)
            \n[**GitHub**](https://github.com/nargesr)
            \n\n
            **Personal Interests:**
            \nI consider myself as an outgoing person, I like camping and adventure. Most weekends, I go hiking with my friends.
            At home, I like cooking, playing board games and playing guitar.
            \n\n
            **Contact:**
            \n nargesr {at} uci.edu
        "
        social:
          - url: https://github.com/nargesr
            icon: fab fa-github
          - url: https://www.linkedin.com/in/narges-rezaie-ab9710b8/
            icon: fab fa-linkedin-in
      - name: "Fairlie Reese"
        id: "fairlie"
        role: "Dev Cell PhD Student"
        lab_role: "Bioinformatician"
        image: assets/img/team/fairlie.jpg
        info: "
            **Research Interests:**
            \nI currently work on long-read transcriptomes, and am specifically focused on developing tools for their analysis.
            \n\n
            **Software:**
            \n[**Swan:**](https://freese.gitbook.io/swan/) a Python library for visualizing and analyzing transcriptomes
            \n[**TALON:**](https://github.com/mortazavilab/TALON) Technology-agnostic long-read annotation and quantification pipeline
            \n\n
            **Links:**
            \n**Personal Website (Coming soon!)**
            \n[**Google Scholar**](https://scholar.google.com/citations?user=SgA5IcgAAAAJ&hl=en)
            \n[**ORCID**](http://orcid.org/0000-0002-9240-0102)
            \n[**LinkedIn**](https://www.linkedin.com/in/fairlie-reese-a930a5b7/)
            \n[**GitHub**](https://github.com/fairliereese)
            \n\n
            **Personal Interests:**
            \nWhen I'm not working (and there's not a pandemic going on) you can find me at the beach, at rock concerts, or eating Mexican food. 
            At home, I like to play video games, Dungeons and Dragons, and hang out with my cats.
            \n\n
            **Contact:**
            \n freese {at} uci.edu
            "
        social:
          - url: https://twitter.com/FairlieReese
            icon: fab fa-twitter
          - url: https://github.com/fairliereese
            icon: fab fa-github
          - url: https://www.linkedin.com/in/fairlie-reese-a930a5b7/
            icon: fab fa-linkedin-in
          # - url: https://orcid.org/0000-0002-9240-0102
          #   icon: fab fa-orcid
      - name: "Gabriela Balderrama-Gutierrez"
        id: "gaby"
        role: "Dev Cell PhD Student"
        image: assets/img/team/gaby.jpg
        info: "Description coming soon"
        social:
          - url: https://twitter.com/Sakuxxy
            icon: fab fa-twitter
          - url: https://github.com/GabyBG
            icon: fab fa-github
          - url: https://www.linkedin.com/in/gabriela-balderrama-gutierrez-0b350914b/
            icon: fab fa-linkedin-in
          # - url: https://orcid.org/0000-0002-5794-4518
          #   icon: fab fa-orcid
      - name: "Elisabeth Rebboah"
        id: "liz"
        role: "MCSB PhD Student"
        image: assets/img/team/liz.jpg
        info: "
          **Research Interests:**
          \nI am interested in NGS-focused biotechnology and currently work on integrating bulk & single-cell/single-nucleus RNA-seq and ATAC-seq in an in vitro model of skeletal muscle differentiation.
          \n\n
          **Links:**
          \n[**ORCID**](http://orcid.org/0000-0003-2273-0189)
          \n[**LinkedIn**](https://www.linkedin.com/in/elisabeth-rebboah-a33923104/)
          \n[**GitHub**](https://github.com/erebboah)
          \n\n
          **Personal Interests:**
          \nI enjoy watching anime and getting takeout when I'm not working.
          \n\n
          **Contact:**
          \n erebboah {at} uci.edu
        "
        social:
          - url: https://twitter.com/LizRebboah
            icon: fab fa-twitter
          - url: https://github.com/erebboah
            icon: fab fa-github
          - url: https://www.linkedin.com/in/elisabeth-rebboah-a33923104/
            icon: fab fa-linkedin-in
      - name: "Christina Wilcox Thai"
        id: "christina"
        role: "Dev Cell PhD Student"
        image: assets/img/team/christina.jpg
        social:
          - url: https://www.linkedin.com/in/christinawilcoxthai/
            icon: fab fa-linkedin-in
      - name: "Klebea Carvalho"
        id: "bea"
        role: "Pharmaceutical Sciences PhD Student"
        image: assets/img/team/bea.jpg
        info: "
          **Research Interests:**
          \nMy research interest spans immunology, neuroscience and genomics-related topics. I evaluate changes in gene expression and chromatin accessibility at bulk and single-cell levels during health and disease states by applying different NGS techniques such as scRNA-seq, snATAC-seq, miRNA-seq and long reads sequencing. 
          \n\n
          **Links:**
          \n[**Google Scholar**](https://scholar.google.com/citations?user=jpc4QIwAAAAJ&hl=en&authuser=2)
          \n[**LinkedIn**](https://www.linkedin.com/in/carvalhoklebea/)
          \n[**GitHub**](https://github.com/kmcarval)
          \n\n
          **Personal Interests:**
          \nI love visiting new countries and learning about new cultures. I also enjoy going on road trips and camping with my husband. I appreciate a good thriller, whether it’s a movie or book, such that I’ve probably read all of the Agatha Christie’s books. I have an adorable cat named Mochi and I play piano and drums.
          \n\n
          **Contact:**
          \n kmcarval {at} uci.edu 
        "
        social:
          - url: https://twitter.com/klebea
            icon: fab fa-twitter
          - url: https://www.linkedin.com/in/carvalhoklebea/
            icon: fab fa-linkedin-in
      - name: "Cassandra McGill"
        id: "cassie"
        role: "Lab Manager / Lab Technician / Sequencing Specialist"
        image: assets/img/team/cassie.jpg
        info: "Description coming soon"
        social:
          - url: https://www.linkedin.com/in/cassandra-mcgill-aa590b123/
            icon: fab fa-linkedin-in
      - name: "Heidi Liang"
        id: "heidi"
        role: "Lab Technician / Sequencing Specialist"
        image: assets/img/team/heidi.jpg
        info: "Description coming soon"
        social:
          - url: https://www.linkedin.com/in/heidi-liang-912331b2/
            icon: fab fa-linkedin-in
      - name: "Katherine Williams"
        id: "kate"
        role: "Dev Cell PhD Student"
        image: assets/img/team/kate.jpg
        info:  "
            **Research Interests:**
            \nI use sequencing technologies to explore epigenetics and gene expression in development of diseases and in non-model organisms.
            \nMy main work in collaboration with the Yokomori lab focuses on investigating the transcriptomeand epigenome in facioscapulohumeral muscular dystrophy (FSHD). I use a variety of techniques such as single-nucleus RNA-seq from multinucleated myotubes, RRBS, and bulk RNA-seq. We aim to uncover how the misexpression of a single transcription factor results in pathogenesis.
            \nI work and collaborate on many other projects including studying the transcriptomes of mammals and nematodes. I love having the opportunity to bring new insights into our understanding of other organisms and ourselves!
            \n\n
            **Links:**
            \n[**Google Scholar**](https://scholar.google.com/citations?user=Lepe9wwAAAAJ&hl=en)
            \n[**ORCID**](http://orcid.org/0000-0001-8061-0105)
            \n[**LinkedIn**](https://www.linkedin.com/in/curlsforscience/)
            \n[**GitHub**](https://github.com/CurlsForScience)
            \n\n
            **Personal Interests:**
            \nI love to dance, specifically lindy hop and east coast swing. I especially love dancing at Disneyland. Most importantly, I enjoy spending time with my dog and being out in the California sun. 
            \n\n
            **Contact:**
            \n kwillia4 {at} uci.edu
            "
        social:
          - url: https://github.com/CurlsForScience
            icon: fab fa-github
          - url: https://www.linkedin.com/in/curlsforscience/
            icon: fab fa-linkedin-in
      - name: "Aide Macias-Muñoz, PhD"
        id: "aide"
        role: "Postdoctoral Fellow"
        image: assets/img/team/aide.jpg
        info: "Description coming soon"
        social:
          - url: https://twitter.com/Aide_Macias
            icon: fab fa-twitter
          - url: https://www.linkedin.com/in/aidemacias/
            icon: fab fa-linkedin-in
      - name: "Ali Mortazavi, PhD"
        id: "ali"
        role: "Principal Investigator"
        image: assets/img/team/ali.jpg
        info: "Description coming soon"
        social:
          - url: https://twitter.com/calizavi
            icon: fab fa-twitter

timeline:
    title: "News" 
    text: "What's happening in the lab?"
    section: timeline
    events:
      - title: "Graduations"
        year: "Spring 2020"
        desc: "We celebrate the graduation of three of our PhD students this spring! Congratulations to Drs. Dana Wyman, Sorena Rahmanian, and Lorrayne Serra Clague! Best of luck to all of you."
        image: assets/img/timeline/diploma.jpg
        alt: 
        align: left
      - title: "snRNA-seq FSHD2 publication"
        year: "May 2020"
        desc: "Kate and Mandy's single-nucleus FSHD2 study, entitled \"Single-nucleus RNA-seq identifies divergent populations of FSHD2 myotube nuclei\", was published in PLoS Genetics. Read it [here](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008754&rev=2)."
        image: assets/img/timeline/muscle.jpg
        alt: 
        align: right
      - title: "Narges joins the lab!"
        year: "March 2020"
        desc: "Narges, an MCSB PhD student, has officially joined the lab! Welcome! She is currently working as a bioinformatician working on the Model AD project."
        image: assets/img/team/narges.jpg
        alt: 
        align: left
      - title: "Hydra vulgaris opsin gene evolution and expression publication"
        year: "December 2019"
        desc: "Aide's Hydra opsin gene study, \"Molecular evolution and expression of opsin genes in Hydra vulgaris\", was published in BMC Genomics. You can read it [here](https://link.springer.com/article/10.1186/s12864-019-6349-y)."
        image: assets/img/timeline/hydra.png
        alt: 
        align: right
      - title: "Gene regulatory networks from scATAC and scRNA-seq linked SOM publication"
        year: "November 2019"
        desc: "Camden's gene-regulatory network study that uses linked SOMs on scATAC and scRNA-seq, \"Building gene regulatory networks from scATAC-seq and scRNA-seq using Linked Self Organizing Maps\", has been published in PLoS Computational Biology. You can read it [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6855564/)."
        image: assets/img/timeline/grn_som.png
        alt: image alt text
    end: ""

past_members:
    title: "Past Members"
    # text: "Past Mortazavi Lab alumni."
    #subtext: ""
    section: past_members
    people:
      - name: "Dana Wyman, PhD"
        id: "dana"
        role: "Former MCSB PhD Student"
        image: assets/img/team/dana.jpg
        info: "Description coming soon"
        social:
          - url: https://twitter.com/DNAwyman
            icon: fab fa-twitter
          - url: https://github.com/dewyman
            icon: fab fa-github
          - url: https://www.linkedin.com/in/dana-wyman/
            icon: fab fa-linkedin-in
          # - url: https://orcid.org/0000-0002-9240-0102
          #   icon: fab fa-orcid
      - name: "Sorena Rahmanian, PhD"
        id: "sorena"
        role: "Former MCSB PhD Student"
        image: assets/img/team/sorena.jpg
        info: "Description coming soon"
        social:
          - url: https://twitter.com/RahmanianSorena
            icon: fab fa-twitter
          - url: https://github.com/sorenar
            icon: fab fa-github
          - url: https://www.linkedin.com/in/sorena-rahmanian/
            icon: fab fa-linkedin-in
          # - url: https://orcid.org/0000-0002-5794-4518
          #   icon: fab fa-orcid
      - name: "Lorrayne Serra Clague, PhD"
        id: "lorrayne"
        role: "Former Dev Cell PhD Student"
        image: assets/img/team/lorrayne.jpg
        info: "Description coming soon"
        social:
          - url: https://www.linkedin.com/in/lorrayne-clague-48120055/
            icon: fab fa-linkedin-in
      - name: "Camden Jansen, PhD"
        id: "camden"
        role: "Former Dev Cell PhD Student"
        image: assets/img/team/camden.jpg
        info: "Description coming soon"
        social:
          - url: https://twitter.com/CamdenJansen
            icon: fab fa-twitter
          - url: https://github.com/csjansen
            icon: fab fa-github
          - url: https://www.linkedin.com/in/camden-jansen-346963196/
            icon: fab fa-linkedin-in

about:
    title: "About Us"
    text: "our story"
    section: about
          
contact:
    title: "Contact Us"
    # text: "Lorem ipsum or call 123456789"
    section: contact
    
footer:
    legal: "Privacy Policy"
    social:
      - url: https://github.com/mortazavilab
        icon: "fab fa-github"


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
