header:
    text: Mortazavi Lab at UC Irvine
    title: Genomics, computation and sequencing

services:
    title: "Research"
    text: "There are many diverse projects going on in the lab"
    section: services
    list:
      - title: "[ENCODE](https://www.encodeproject.org/)"
        desc: "We are an ENCODE production lab and produce and analyze long-read and micro RNA-seq datasets for the consortium."
        icon: fas fa-dna #find more at https://fontawesome.com/icons
      - title: "[Model AD](https://www.model-ad.org/)"
        desc: "Working towards developing a more comprehensive mouse model for Alzheimer's Disease."
        icon: fas fa-brain       
      - title: "FSHD"
        desc: "Understanding the mechanisms behind the pathology in Facioscapulohumeral muscular dystrophy."
        icon: fas fa-male


portfolio:
    title: "Software"
    text: "Software produced by the lab used to analyze genomics data"
    section: portfolio
    
team:
    title: "People"
    # text: "Our wonderful team of graduate students possesses a diverse set of skills in both data generation and analysis."
    # subtext: All of our all-star graduate students are proficient both at the bench and at the terminal! You guys rock!
    section: team
    people:
      - name: "Narges Rezaie"
        id: "narges"
        role: "MCSB PhD Student"
        image: assets/img/team/narges.png
        social:
          - url: https://github.com/nargesr
            icon: fab fa-github
          - url: https://www.linkedin.com/in/narges-rezaie-ab9710b8/
            icon: fab fa-linkedin-in
      - name: "Fairlie Reese"
        id: "fairlie"
        role: "Dev Cell PhD Student"
        image: assets/img/team/fairlie.jpg
        social:
          - url: https://twitter.com/FairlieReese
            icon: fab fa-twitter
          - url: https://github.com/fairliereese
            icon: fab fa-github
          - url: https://www.linkedin.com/in/fairlie-reese-a930a5b7/
            icon: fab fa-linkedin-in
          # - url: https://orcid.org/0000-0002-9240-0102
          #   icon: fab fa-orcid
      - name: "Gabriela Balderrama-Gutierrez"
        id: "gaby"
        role: "Dev Cell PhD Student"
        image: assets/img/team/gaby.jpg
        social:
          - url: https://twitter.com/Sakuxxy
            icon: fab fa-twitter
          - url: https://github.com/GabyBG
            icon: fab fa-github
          - url: https://www.linkedin.com/in/gabriela-balderrama-gutierrez-0b350914b/
            icon: fab fa-linkedin-in
          # - url: https://orcid.org/0000-0002-5794-4518
          #   icon: fab fa-orcid
      - name: "Elisabeth Rebboah"
        id: "liz"
        role: "MCSB PhD Student"
        image: assets/img/team/liz.jpg
        social:
          - url: https://twitter.com/LizRebboah
            icon: fab fa-twitter
          - url: https://github.com/erebboah
            icon: fab fa-github
          - url: https://www.linkedin.com/in/elisabeth-rebboah-a33923104/
            icon: fab fa-linkedin-in
      - name: "Christina Wilcox Thai"
        id: "christina"
        role: "Dev Cell PhD Student"
        image: assets/img/team/christina.jpg
        social:
          - url: https://www.linkedin.com/in/christinawilcoxthai/
            icon: fab fa-linkedin-in
      - name: "Klebea Carvalho"
        id: "bea"
        role: "Pharmaceutical Sciences PhD Student"
        image: assets/img/team/bea.jpg
        social:
          - url: https://twitter.com/klebea
            icon: fab fa-twitter
          - url: https://www.linkedin.com/in/carvalhoklebea/
            icon: fab fa-linkedin-in
      - name: "Cassandra McGill"
        id: "cassie"
        role: "Lab Manager / Lab Technician / Sequencing Specialist"
        image: assets/img/team/cassie.jpg
        social:
          - url: https://www.linkedin.com/in/cassandra-mcgill-aa590b123/
            icon: fab fa-linkedin-in
      - name: "Heidi Liang"
        id: "heidi"
        role: "Lab Technician / Sequencing Specialist"
        image: assets/img/team/heidi.jpg
        social:
          - url: https://www.linkedin.com/in/heidi-liang-912331b2/
            icon: fab fa-linkedin-in
      - name: "Katherine Williams"
        id: "kate"
        role: "Dev Cell PhD Student"
        image: assets/img/team/kate.jpg
        social:
          - url: https://www.linkedin.com/in/curlsforscience/
            icon: fab fa-linkedin-in
      - name: "Aide Macias-Muñoz, PhD"
        id: "aide"
        role: "Postdoctoral Fellow"
        image: assets/img/team/aide.jpg
        social:
          - url: https://twitter.com/Aide_Macias
            icon: fab fa-twitter
          - url: https://www.linkedin.com/in/aidemacias/
            icon: fab fa-linkedin-in
      - name: "Ali Mortazavi, PhD"
        id: "ali"
        role: "Principal Investigator"
        image: assets/img/team/ali.jpg
        social:
          - url: https://twitter.com/calizavi
            icon: fab fa-twitter

timeline:
    title: "News" 
    text: "What's happening in the lab?"
    section: timeline
    events:
      - title: "Graduations"
        year: "Spring 2020"
        desc: "We celebrate the graduation of three of our PhD students this spring! Congratulations to Drs. Dana Wyman, Sorena Rahmanian, and Lorrayne Serra Clague! Best of luck to all of you."
        image: assets/img/timeline/diploma.jpg
        alt: 
        align: left
      - title: "snRNA-seq FSHD2 publication"
        year: "May 2020"
        desc: "Kate and Mandy's single-nucleus FSHD2 study, entitled \"Single-nucleus RNA-seq identifies divergent populations of FSHD2 myotube nuclei\", was published in PLoS Genetics. Read it [here](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008754&rev=2)."
        image: assets/img/timeline/muscle.jpg
        alt: 
        align: right
      - title: "Narges joins the lab!"
        year: "March 2020"
        desc: "Narges, an MCSB PhD student, has officially joined the lab! Welcome! She is currently working as a bioinformatician working on the Model AD project."
        image: assets/img/team/narges.jpg
        alt: 
        align: left
      - title: "Hydra vulgaris opsin gene evolution and expression publication"
        year: "December 2019"
        desc: "Aide's Hydra opsin gene study, \"Molecular evolution and expression of opsin genes in Hydra vulgaris\", was published in BMC Genomics. You can read it [here](https://link.springer.com/article/10.1186/s12864-019-6349-y)."
        image: assets/img/timeline/hydra.png
        alt: 
        align: right
      - title: "Gene regulatory networks from scATAC and scRNA-seq linked SOM publication"
        year: "November 2019"
        desc: "Camden's gene-regulatory network study that uses linked SOMs on scATAC and scRNA-seq, \"Building gene regulatory networks from scATAC-seq and scRNA-seq using Linked Self Organizing Maps\", has been published in PLoS Computational Biology. You can read it [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6855564/)."
        image: assets/img/timeline/grn_som.png
        alt: image alt text
    end: ""

past_members:
    title: "Past Members"
    # text: "Past Mortazavi Lab alumni."
    section: past_members
    people:
      - name: "Dana Wyman, PhD"
        id: "dana"
        role: "Former MCSB PhD Student"
        image: assets/img/team/dana.jpg
        social:
          - url: https://twitter.com/DNAwyman
            icon: fab fa-twitter
          - url: https://github.com/dewyman
            icon: fab fa-github
          - url: https://www.linkedin.com/in/dana-wyman/
            icon: fab fa-linkedin-in
          # - url: https://orcid.org/0000-0002-9240-0102
          #   icon: fab fa-orcid
      - name: "Sorena Rahmanian, PhD"
        id: "sorena"
        role: "Former MCSB PhD Student"
        image: assets/img/team/sorena.jpg
        social:
          - url: https://twitter.com/RahmanianSorena
            icon: fab fa-twitter
          - url: https://github.com/sorenar
            icon: fab fa-github
          - url: https://www.linkedin.com/in/sorena-rahmanian/
            icon: fab fa-linkedin-in
          # - url: https://orcid.org/0000-0002-5794-4518
          #   icon: fab fa-orcid
      - name: "Lorrayne Serra Clague, PhD"
        id: "lorrayne"
        role: "Former Dev Cell PhD Student"
        image: assets/img/team/lorrayne.jpg
        social:
          - url: https://www.linkedin.com/in/lorrayne-clague-48120055/
            icon: fab fa-linkedin-in
      - name: "Camden Jansen, PhD"
        id: "camden"
        role: "Former Dev Cell PhD Student"
        image: assets/img/team/camden.jpg
        social:
          - url: https://twitter.com/CamdenJansen
            icon: fab fa-twitter
          - url: https://github.com/csjansen
            icon: fab fa-github
          - url: https://www.linkedin.com/in/camden-jansen-346963196/
            icon: fab fa-linkedin-in

about:
    title: "About Us"
    text: "our story"
    section: about
          
contact:
    title: "Contact Us"
    # text: "Lorem ipsum or call 123456789"
    section: contact
    
footer:
    legal: "Privacy Policy"
    social:
      - url: https://twitter.com
        icon: "fab fa-twitter"  
      - url: https://facebook.com
        icon: "fab fa-facebook-f"
      - url: https://linkedin.com
        icon: "fab fa-linkedin-in"
      - url: https://github.com/raviriley/agency-jekyll-theme
        icon: "fab fa-github"
      - url: https://instagram.com
        icon: "fab fa-instagram"


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
